# Generated by Django 3.2.5 on 2022-08-23 10:56

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoid', models.CharField(max_length=100, unique=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('participants_summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('study_design', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BodySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodysite', models.CharField(default=None, max_length=100)),
                ('sampletype', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ['bodysite'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('doid', models.IntegerField(default=None, null=True)),
            ],
            options={
                'ordering': ['disease'],
            },
        ),
        migrations.CreateModel(
            name='LocEthDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(default=None, max_length=100, null=True)),
                ('urbanization', models.CharField(default=None, max_length=50, null=True)),
                ('cityvillage', models.CharField(default=None, max_length=50, null=True)),
                ('ethnicity', models.CharField(default=None, max_length=50, null=True)),
                ('elo', models.CharField(default=None, max_length=20, null=True)),
                ('el_wiki', models.CharField(default=None, max_length=100, null=True)),
                ('diets', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['country', 'region', 'urbanization', 'cityvillage', 'ethnicity', 'elo', 'diets'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('assay', models.CharField(default=None, max_length=100, null=True)),
                ('target_amplicon', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['platform', 'technology', 'assay', 'target_amplicon'],
            },
        ),
        migrations.CreateModel(
            name='Pubmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['pubid', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoid', models.CharField(max_length=100)),
                ('sample_size', models.IntegerField(default=0)),
                ('pubid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=2000)),
                ('study_design', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(default=None, max_length=100, null=True)),
                ('urbanization', models.CharField(default=None, max_length=50, null=True)),
                ('cityvillage', models.CharField(default=None, max_length=50, null=True)),
                ('ethnicity', models.CharField(default=None, max_length=50, null=True)),
                ('elo', models.CharField(default=None, max_length=20, null=True)),
                ('diets', models.CharField(default=None, max_length=100, null=True)),
                ('platform', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('assay', models.CharField(default=None, max_length=100, null=True)),
                ('target_amplicon', models.CharField(default=None, max_length=50, null=True)),
                ('bodysite', models.CharField(max_length=100)),
                ('participant_feature', models.CharField(blank=True, max_length=1000, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('disease', models.CharField(max_length=100)),
                ('doid', models.CharField(default=None, max_length=100, null=True)),
                ('sampid', models.CharField(max_length=100)),
                ('avspotlen', models.IntegerField()),
                ('col_date', models.DateField(default=None, null=True)),
                ('lib_layout', models.CharField(max_length=20)),
                ('coordinate', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', taggit.managers.TaggableManager(help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampid', models.CharField(max_length=100, unique=True)),
                ('avspotlen', models.IntegerField(blank=True, null=True)),
                ('participant_feature', models.CharField(blank=True, max_length=1000, null=True)),
                ('col_date', models.DateField(default=None, null=True)),
                ('lib_layout', models.CharField(max_length=20)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('capital', models.BooleanField(default=False)),
                ('is_mixed', models.BooleanField(default=False)),
                ('l2bioproject', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MicroBiome.bioproject')),
                ('l2bodysite', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MicroBiome.bodysite')),
                ('l2disease', models.ManyToManyField(to='MicroBiome.Disease')),
                ('l2loc_diet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MicroBiome.locethdiet')),
                ('l2platform', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MicroBiome.platform')),
                ('l2pubmed', models.ManyToManyField(to='MicroBiome.Pubmed')),
            ],
            options={
                'ordering': ['sampid'],
            },
        ),
    ]
