# Generated by Django 3.2.2 on 2021-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodysite', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['bodysite'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, default=None, max_length=100)),
                ('doid', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['disease'],
            },
        ),
        migrations.CreateModel(
            name='LocEthDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('urbanization', models.CharField(max_length=100)),
                ('cityvillage', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('elo', models.CharField(max_length=100)),
                ('diets', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=50, null=True)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('capital', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'region', 'lon', 'lat'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default=None, max_length=100, null=True)),
                ('technology', models.CharField(max_length=100)),
                ('assay', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['platform', 'technology', 'assay'],
            },
        ),
        migrations.CreateModel(
            name='Pubmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['pubid', 'title'],
            },
        ),
    ]
